# Start from a base Java image
FROM openjdk:18-jdk-alpine

# Set working directory
WORKDIR /app

# Copy the built jar file into the image
COPY target/expensetracker-0.0.1-SNAPSHOT.jar app.jar

# Expose the port Spring Boot runs on
EXPOSE 8080

# Command to run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
